name: azure deploy CI

on: 
  push:
    branches:
    - master
  
# Packages and deploys backend code to Azure
# Only runs when there is a push to the master branch  
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
           pushd Code/Backend/waitless-functions
           mvn clean package
           mvn azure-functions:package
           popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: waitless-functions-20200207161542196
        package: ./Code/Backend/waitless-functions//target/azure-functions/waitless-functions-20200207161542196
      
