name: mvn test CI

on: [push]

jobs:
  build:

#Build docker image 
#WIP does not run all mvn tests currently
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build the Docker image
          run: |
                pushd Code/Backend/waitless-functions
                docker build .
                popd
      
